// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationWebAPI.Data;

#nullable disable

namespace RegistrationWebAPI.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20260428011332_AddMemberOrganisationSchema")]
    partial class AddMemberOrganisationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("RegistrationShared.Models.MemberOrganisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MembershipEstablishmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationDomain")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationDomain")
                        .IsUnique();

                    b.ToTable("MemberOrganisations");
                });

            modelBuilder.Entity("RegistrationShared.Models.MemberOrganisationRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgreesToTerms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicenceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberOrganisationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberOrganisationId");

                    b.ToTable("MemberOrganisationRegistration");
                });

            modelBuilder.Entity("RegistrationWebAPI.Data.RegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgreesToTerms")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnnualTurnover")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationSentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicencePathway")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicenceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDate");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("EmailVerificationToken")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("RegistrationShared.Models.MemberOrganisationRegistration", b =>
                {
                    b.HasOne("RegistrationShared.Models.MemberOrganisation", "MemberOrganisation")
                        .WithMany("MemberRegistrations")
                        .HasForeignKey("MemberOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberOrganisation");
                });

            modelBuilder.Entity("RegistrationShared.Models.MemberOrganisation", b =>
                {
                    b.Navigation("MemberRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
