// <auto-generated />
using System;
using RegistrationWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistrationWebAPI.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    partial class RegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("APSIM.RegistrationAPIV2.Data.RegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnnualTurnover")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicencePathway")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicenceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganisationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDate");

                    b.HasIndex("ContactEmail");

                    b.ToTable("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
